services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    ports:
      - "8080:8080"

  postgres:
    ports:
      - "5432:5432"
